import re

text='''Regular expressions can be concatenated to form
new regular expressions; if A and B are both regular
expressions, then AB is also a regular expression. In 
general, if a string p matches A and another string q 
matches B, the string pq will match AB. This holds unless A or B contain low precedence operations; boundary conditions between A and B; or have numbered group references. Thus, complex expressions can easily be constructed from simpler primitive expressions like the ones described here. For details of the theory and implementation of regular expressions, 
consult the Friedl booцв k [Frie09], or almost any textbook 
about compiler construction'''

javob=re.findall('[А-Я]',text)

print(len(javob))